# Generated by Django 4.0.1 on 2022-01-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_expenses_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQueries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('query', models.CharField(max_length=1000)),
                ('is_solved', models.BooleanField()),
            ],
        ),
    ]
