# Generated by Django 4.0.1 on 2022-01-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_expenses_app', '0002_userqueries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userqueries',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
