# Generated by Django 4.0.1 on 2022-01-16 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_expenses_app', '0004_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='ExpensesGroup',
        ),
    ]
