# Generated by Django 4.0.1 on 2022-01-16 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_expenses_app', '0005_rename_group_expensesgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensesgroup',
            name='members',
        ),
        migrations.AddField(
            model_name='expensesgroup',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
