# Generated by Django 4.0.1 on 2022-01-16 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_expenses_app', '0006_remove_expensesgroup_members_expensesgroup_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensesgroup',
            old_name='name',
            new_name='group_name',
        ),
        migrations.AddField(
            model_name='expensesgroup',
            name='group_picture',
            field=models.ImageField(blank=True, null=True, upload_to='group_pictures'),
        ),
        migrations.AddField(
            model_name='expensesgroup',
            name='group_type',
            field=models.CharField(choices=[('Friends', 'Friends'), ('Trip', 'Trip'), ('Home', 'Home'), ('Couple', 'Couple'), ('Other', 'Other')], default='Friends', max_length=200),
        ),
        migrations.AlterField(
            model_name='baseuserprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picures'),
        ),
        migrations.AlterField(
            model_name='expensesgroup',
            name='members',
            field=models.ManyToManyField(related_name='groups_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=1000)),
                ('split_type', models.CharField(choices=[('Equally', 'Equally'), ('Unequally', 'Unequally'), ('By percentages', 'By Percentages')], max_length=100)),
                ('amount_you_have_to_pay', models.IntegerField(default=0)),
                ('amount_you_will_receive', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(max_length=500)),
                ('is_setteled', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to=settings.AUTH_USER_MODEL)),
                ('with_whom_to_split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='with_whom_to_split', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_message', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_expenses_app.expense')),
            ],
        ),
        migrations.AddField(
            model_name='expensesgroup',
            name='expenses',
            field=models.ManyToManyField(blank=True, related_name='groups_list_for_this_expense', to='manage_expenses_app.Expense'),
        ),
    ]
